### ISSUE TITLE
Enhancement: Containers should have resource request and limits set by default

### ISSUE THREAD

**Issue by guibirow** [Ensono/amido.github.io#20]
**Feature, tool or process you are suggesting improvement for:**

The current deployment files for kubernetes resources does not define resource requests and limits and should provide some values to induce people of using this feature.
Ignoring the use of resource limits may cause issues under load given the containers will start to compete for resources and be killed frequently.
As reference implementation, these should be always set.

**How you suggest to improve it:**

Identify the average consumption of current implementation and add these to the deployment file as example below:

```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: wp
    image: wordpress
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

for more information check the [docs](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/)
